language: python

os:
  - linux

sudo: false

cache: pip

python:
  - "3.6"
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -v .

script:
  #  - 'python setup.py test --tox-args="-e$TOX_ENV"'
  - 'py.test'
  - 'pycodestyle'

#env:
#  #- TOX_ENV=py27
#  #- TOX_ENV=py34
#  #- TOX_ENV=py35
#  - TOX_ENV=py36
#  #- TOX_ENV=pypy
#  #- TOX_ENV=pypy3
#  - TOX_ENV=docs
#  - TOX_ENV=pep8

